## Settings affecting Tumblr
Tumblr:
    PostsPerPage: 10

# Locations for theme and data files
#
# You may use any type of path. Examples:
#
# themes/Redux.html (relative to this file)
# ~/themes/Redux.html (in your user directory)
# /Library/WebServer/Documents/themes/Redux.html (absolute path)
ThemeFile: "themes/Redux.html"
DataFile: "data/demo.yml"
